### ISSUE TITLE
Pretrained models?

### ISSUE THREAD

**Issue by wassname** [robertomest/convnet-study#1]
It's great to see the training schedules and the difference data augmentation makes. Would you consider sharing the weights of the pretrained models? I'm interested in the densenet one especially.

**Comment by robertomest** [comment]
Hello @wassname , I apologize for the delay. I've uploaded some pretrained Densenet model weights for CIFAR10 for you: a Densenet-40,12 and a Densenet-BC-100,12 trained both with and without augmentation. You should be able to download them through this link: https://www.dropbox.com/sh/tlotbirhqljlrc8/AACxKmUFcdMZ3rTWFIZIUNXfa?dl=0. Let me know if these are helpful to you.

**Comment by wassname** [comment]
That's great, thanks for that!
